version: "3.8"

services:
  microservices_mysql:
    image: mysql:9.1.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data_microservices_mysql:/var/lib/mysql

  microservices_template:
    restart: always
    env_file:
      - .env
    depends_on:
      - microservices_mysql

volumes:
  data_microservices_mysql:
