"""add name, age, email, created_at column to user table

Revision ID: 230faeb59c3b
Revises: 1f66792fa80e
Create Date: 2024-10-24 03:53:28.426672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230faeb59c3b'
down_revision: Union[str, None] = '1f66792fa80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'email')
    op.drop_column('users', 'age')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
